### ISSUE TITLE
RandomPkg_user_guide Typo

### ISSUE THREAD

**Issue by Greek64** [OSVVM/Documentation#2]
In `RandomPkg_user_guide.pdf` page 7 it reads
```
-- Generate 10 integer values in the range 0 to 255, do repeat the last value
IntV(1 to 10) := RV.RandIntV(0, 255, 1, 10) ;
```

My guess is that should read `do NOT repeat the last value`, similarly to the other functions

**Comment by JimLewis** [comment]
Thank you.   It has been updated in the documentation repository.
